from pipeline_ofer_funcs import *
import time
"""
=========================================================================================
SPATIAL AUDIO SEPARATION PIPELINE
=========================================================================================
This module implements an offline, multi-microphone spatial audio separation system.
It is designed to take a raw mixed audio recording and a set of pre-calculated tracking
labels (CSD: Concurrent Speaker Detection, and DOA: Direction of Arrival) to isolate
individual speakers from background noise.

Algorithm Overview:
1. Domain Shift: Converts multi-channel time-domain audio into the frequency domain (STFT).
2. Noise Estimation: Uses periods of silence (CSD=0) to build a spatial noise covariance
   matrix (Qvv).
3. Speaker Fingerprinting: Uses single-speaker periods (CSD=1) and their DOA labels to
   estimate the Relative Transfer Function (RTF) via Generalized Eigenvalue Decomposition
   (GEVD). This creates a spatial "fingerprint" (G) for each speaker.
4. Beamforming: Applies Minimum Variance Distortionless Response (MVDR) for single speakers,
   or Linearly Constrained Minimum Variance (LCMV) beamforming for overlapping speakers,
   actively suppressing noise and cross-talk.
5. Synthesis: Converts the separated frequency frames back into listenable audio (ISTFT).
=========================================================================================
"""

class SpatialSeparationPipeline:
    """
    Orchestrates the entire spatial separation algorithm via a state-machine architecture.

    The class is divided into five logical phases:

    1. INGESTION (`load_data`):
       Loads the mixed audio, clean references (optional, for grading), and the CSD/DOA
       tracking labels generated by the upstream neural network pipeline.

    2. TRANSFORMATION (`compute_stft`):
       Shifts the audio from waveforms into a 3D time-frequency matrix [frames, freq, mics]
       so overlapping voices can be mathematically untangled.

    3. THE ONLINE ENGINE (`run_online_separation` & private helpers):
       Steps through time frame-by-frame, using the CSD label as a traffic router:
       - CSD 0: Updates the background noise matrix (`_update_noise_covariance`).
       - CSD 1: Manages active speaker "slots" and candidate persistence, calculating the
                spatial fingerprint (GEVD RTF) for the active speaker (`_update_rtf_and_tracking`).
       - CSD 2: Flags that both established speaker slots are currently active.

    4. FILTERING (`_compute_spatial_filters`):
       Acts as a highly directional virtual lens. Depending on how many speakers are currently
       active, it builds either an MVDR or LCMV spatial filter to isolate the target voices.

    5. SYNTHESIS & EVALUATION (`reconstruct_audio`, `evaluate_and_save`):
       Stitches the separated frequency frames back into listenable .wav files. If reference
       files were provided, it automatically calculates BSS Eval (SDR/SIR) and SI-SDR metrics.
    """
    def __init__(self, run_idx, p_stft, p_tracking, p_beamforming, folder_to_test_data, folder_to_results, M=4, num_speech=2, verbose=1):
        """
        Initializes the spatial separation pipeline.
        Args:
            run_idx (int): The ID number of the experiment (e.g., 3).
            p_stft (dict): Configuration for STFT parameters.
            p_tracking (dict): Configuration for tracking thresholds and context windows.
            p_beamforming (dict): Configuration for beamforming parameters and smoothing factors.
            folder_to_test_data (str): Path to the directory containing the raw test data.
            folder_to_results (str): Path to the directory where results will be saved.
            M (int): Number of microphone channels to process.
            num_speech (int): Number of simultaneous speakers to separate.
            verbose (int): Level of logging detail (0: none, 1: key steps, 2: detailed).
        """
        self.run_idx = run_idx
        self.p_stft = p_stft
        self.p_tracking = p_tracking
        self.p_beamforming = p_beamforming
        self.folder_to_test_data = folder_to_test_data
        self.folder_to_results = folder_to_results
        self.M = M
        self.num_speech = num_speech
        self.verbose = verbose

        # Audio & Labels
        self.fs = None
        self.z_k = None
        self.z_k_first = None
        self.z_k_second = None
        self.y_prob_stat_mf = None
        self.y2_prob_stat_mf = None
        self.y_mf = None  # True CSD for overlap evaluation bounds
        self.evaluate = False # Flag set to True if reference files are successfully loaded

        # State Variables
        self.NUP = self.p_stft['NUP']
        self.buffer_size = self.p_beamforming['buffer_size']

        self.Qvv = np.zeros((self.NUP, self.M, self.M), dtype=complex)
        for j in range(self.NUP):
            self.Qvv[j, :, :] = np.eye(self.M)
        self.Qvv_temp = np.zeros((self.NUP, self.M, self.M), dtype=complex)

        self.G = np.ones((self.NUP, self.M, self.num_speech), dtype=complex)
        self.W = None # Instantiated dynamically once frame count is known
        self.s_hat_total = None

        self.PSD_matrix_per_DOA = np.zeros((18, self.NUP, self.M, self.M), dtype=complex)
        self.total_frame_per_DOA = np.zeros(18)
        self.stand_z = np.empty((0, self.NUP, self.M), dtype=complex)

        # Frame classification system layout:
        # row 0 -> [active_DOA_slot_0, active_DOA_slot_1, candidate_DOA]
        # row 1 -> [frame_count_slot_0, frame_count_slot_1, frame_count_candidate]
        self.Frame_classification_system = np.zeros((2, 3))

        # Rolling context windows
        self.save_last_frames_first = np.zeros((self.buffer_size, self.NUP, self.M), dtype=complex)
        self.save_last_frames_doa_first = np.zeros(self.buffer_size)
        self.save_last_frames_second = np.zeros((self.buffer_size, self.NUP, self.M), dtype=complex)
        self.save_last_frames_doa_second = np.zeros(self.buffer_size)

        # Trackers
        self.time_first = 0
        self.time_second = 0
        self.first_speaker_active = 0
        self.second_speaker_active = 0
        self.flag_first_noise = 0
        self.sum_Qvv = 0
        self.flag_start_lcmv = 1
        self.alfa_Qvv = self.p_beamforming['alfa_Qvv_init']

    def load_data(self):
        """Loads mixed audio, labels, and optionally clean references for evaluation."""
        if self.verbose:
            print(f"--- Loading data for Experiment {self.run_idx} ---")

        signal_file = os.path.join(self.folder_to_test_data, f'together_{self.run_idx}.wav')
        self.fs, receivers = wavfile.read(signal_file)
        self.receivers = receivers[:, :self.M] / np.max(np.abs(receivers))

        # Load tracked outputs from the results folder
        self.y2_prob_stat_mf = np.load(os.path.join(self.folder_to_results, f'estimate_DOA_{self.run_idx}.npy'))
        self.y_prob_stat_mf = np.load(os.path.join(self.folder_to_results, f'estimate_CSD_{self.run_idx}.npy'))

        # Optional: Load reference signals for evaluation
        try:
            _, ref_first = wavfile.read(os.path.join(self.folder_to_test_data, f'first_{self.run_idx}.wav'))
            _, ref_second = wavfile.read(os.path.join(self.folder_to_test_data, f'second_{self.run_idx}.wav'))

            self.receiver_first = ref_first[:, :self.M] / np.max(np.abs(ref_first))
            self.receiver_second = ref_second[:, :self.M] / np.max(np.abs(ref_second))

            # Ground truth CSD is usually saved in the results folder by the tracking pipeline
            self.y_mf = np.load(os.path.join(self.folder_to_results, f'true_CSD_{self.run_idx}.npy'))
            self.evaluate = True
            if self.verbose > 1: print("Reference files found. Evaluation metrics will be computed.")
        except FileNotFoundError:
            self.evaluate = False
            if self.verbose > 1: print("Reference files not found. Skipping evaluation metrics.")

        self.W = np.ones((len(self.y2_prob_stat_mf), self.NUP, self.M, self.num_speech), dtype=complex)

    def compute_stft(self):
        """Transforms signals into the time-frequency domain and applies trimming."""
        if self.verbose:
            print("--- Computing STFTs ---")

        win = self.p_stft['win']
        hop = self.p_stft['hop']
        nfft = self.p_stft['nfft']
        f_before = self.p_tracking['frame_before']
        f_after = self.p_tracking['frame_after']

        index = int(1 + np.fix((len(self.receivers[:, 1]) - self.p_stft['wlen']) / hop))

        def do_stft(audio):
            z = np.zeros((self.M, self.NUP, index), dtype=complex)
            for i in range(self.M):
                z[i, :, :] = stft(audio[:, i], win, hop, nfft)
            z = np.transpose(z, (2, 1, 0)) # -> [frame, freq, mic]
            return z[f_before:index - f_after, :, :]

        self.z_k = do_stft(self.receivers)

        if self.evaluate:
            self.z_k_first = do_stft(self.receiver_first)
            self.z_k_second = do_stft(self.receiver_second)

    def _update_noise_covariance(self, l):
        """Handles CSD=0 (Noise-only frames) using batched matrix operations."""
        self.time_second += 1
        self.time_first += 1

        # 1. Extract the current frame for all frequencies: Shape (NUP, M)
        z_frame = self.z_k[l]

        # 2. Reshape for batched outer product
        # z_col: (NUP, M, 1) | z_row: (NUP, 1, M)
        z_col = z_frame[:, :, np.newaxis]
        z_row = z_frame[:, np.newaxis, :].conj()

        # 3. Calculate instantaneous covariance for all NUP bins at once: (NUP, M, M)
        # This replaces the Qvv_temp global array with a readable intermediate variable
        Qvv_inst = z_col @ z_row

        if self.flag_first_noise == 0:
            self.flag_first_noise = 1
            self.Qvv = Qvv_inst.copy()
            self.sum_Qvv = 1
        else:
            self.sum_Qvv += 1
            self.alfa_Qvv = self.p_beamforming['alfa_Qvv_run']
            # Broadcast scalar smoothing across the entire 3D tensor
            self.Qvv = (1 - self.alfa_Qvv) * self.Qvv + (self.alfa_Qvv) * Qvv_inst

    def _update_rtf_and_tracking(self, l):
        """Handles CSD=1 (Single speaker active). Manages slots and GEVD."""
        y2_prob = self.y2_prob_stat_mf[l]
        epsilon = self.p_beamforming['epsilon']

        # Push to context buffer if near an active slot
        if abs(y2_prob - self.Frame_classification_system[0, 0]) < 3 and self.Frame_classification_system[0, 0] != 0:
            self.save_last_frames_first = np.roll(self.save_last_frames_first, 1, axis=0)
            self.save_last_frames_first[0] = self.z_k[l]
            self.save_last_frames_doa_first = np.roll(self.save_last_frames_doa_first, 1)
            self.save_last_frames_doa_first[0] = y2_prob

        elif abs(y2_prob - self.Frame_classification_system[0, 1]) < 3 and self.Frame_classification_system[0, 0] != 0:
            self.save_last_frames_second = np.roll(self.save_last_frames_second, 1, axis=0)
            self.save_last_frames_second[0] = self.z_k[l]
            self.save_last_frames_doa_second = np.roll(self.save_last_frames_doa_second, 1)
            self.save_last_frames_doa_second[0] = y2_prob

        # SLOT 0 UPDATE
        if y2_prob == self.Frame_classification_system[0, 0]:
            self._update_slot(0, y2_prob, l, self.save_last_frames_first, self.save_last_frames_doa_first)

        # SLOT 1 UPDATE
        elif y2_prob == self.Frame_classification_system[0, 1]:
            self._update_slot(1, y2_prob, l, self.save_last_frames_second, self.save_last_frames_doa_second)

        # CANDIDATE DOA PERSISTENCE BRANCH
        elif y2_prob == self.Frame_classification_system[0, 2]:
            self._process_candidate_doa(l, y2_prob)

        # START TRACKING NEW CANDIDATE
        else:
            self.stand_z = self.z_k[l, :, :].reshape(1, self.NUP, self.M)
            self.Frame_classification_system[0, 2] = y2_prob
            self.Frame_classification_system[1, 2] = 1
            self.time_second += 1
            self.time_first += 1

    def _update_slot(self, slot_idx, y2_prob, l, save_last_frames, save_last_frames_doa):
        """Helper to compute batched GEVD RTF for an active slot."""
        epsilon = self.p_beamforming['epsilon']

        self.Frame_classification_system[1, slot_idx] += 1
        self.Frame_classification_system[1, 2] = 0
        self.Frame_classification_system[0, 2] = 0

        if slot_idx == 0:
            self.time_first = 0
            self.time_second += 1
        else:
            self.time_second = 0
            self.time_first += 1

        # Extract valid historical frames
        curr_frames = save_last_frames[np.where(save_last_frames_doa > 0)]
        curr_doa = save_last_frames_doa[np.where(save_last_frames_doa > 0)]
        curr_frames = curr_frames[np.where(abs(curr_doa - y2_prob) != 0)]
        curr_doa = save_last_frames_doa[np.where(abs(curr_doa - y2_prob) != 0)]
        curr_frames = curr_frames[np.where(abs(curr_doa - y2_prob) < 3)]

        self.total_frame_per_DOA[y2_prob - 1] += 1
        alfa_G = (1 + len(curr_frames)) / (self.total_frame_per_DOA[y2_prob - 1] + len(curr_frames))

        # 1. Assemble Batched Signal Matrix
        # Current frame: (NUP, M, 1)
        z_frame = self.z_k[l, :, :, np.newaxis]
        if len(curr_frames) > 0:
            # Transpose history from (Frames, NUP, M) -> (NUP, M, Frames)
            history_trans = curr_frames.transpose(1, 2, 0)
            # Concatenate along the frame axis -> (NUP, M, Frames + 1)
            all_frames = np.concatenate((z_frame, history_trans), axis=2)
        else:
            all_frames = z_frame

        # 2. Batched Cholesky and Inversion
        chol_Qvv = LA.cholesky(self.Qvv) # (NUP, M, M)
        norm_chol = LA.norm(chol_Qvv, axis=(1, 2), keepdims=True)
        chol_inv = LA.inv(chol_Qvv + epsilon * norm_chol * np.eye(self.M))

        # 3. Batched Whitening and Covariance
        # (NUP, M, M) @ (NUP, M, Frames+1) -> (NUP, M, Frames+1)
        a = chol_inv @ all_frames
        # Outer product across the frame axis -> (NUP, M, M)
        Zvv_temp = a @ a.conj().transpose(0, 2, 1)

        # Smooth PSD matrix
        self.PSD_matrix_per_DOA[y2_prob - 1] = (1 - alfa_G) * self.PSD_matrix_per_DOA[y2_prob - 1] + (alfa_G) * Zvv_temp

        # 4. Batched Eigendecomposition
        w, v = LA.eig(self.PSD_matrix_per_DOA[y2_prob - 1])

        # Find index of max REAL eigenvalue for each frequency bin -> shape (NUP,)
        max_idx = np.argmax(w.real, axis=1)

        # Fancy indexing: extract the dominant eigenvector for each frequency
        # v[np.arange(self.NUP), :, max_idx] -> (NUP, M). Then add axis -> (NUP, M, 1)
        phi = v[np.arange(self.NUP), :, max_idx][:, :, np.newaxis]

        # 5. Batched Recolor and Normalize
        numerator = chol_Qvv @ phi  # (NUP, M, 1)
        # Denominator: Isolate reference mic (row 0) -> (NUP, 1, M) @ (NUP, M, 1) -> (NUP, 1, 1)
        denominator = chol_Qvv[:, 0:1, :] @ phi

        # Divide, squeeze out dummy dimension, and save to G
        self.G[:, :, slot_idx] = np.squeeze(numerator / denominator, axis=2)

    def _process_candidate_doa(self, l, y2_prob):
        """Helper to promote a candidate DOA to an active slot using batched ops."""
        epsilon = self.p_beamforming['epsilon']
        thresh = self.p_tracking['threshold_chage_location']

        # Append current frame to candidate buffer
        self.stand_z = np.concatenate((self.stand_z, self.z_k[l, :, :].reshape(1, self.NUP, self.M)))
        self.Frame_classification_system[1, 2] += 1
        self.time_second += 1
        self.time_first += 1

        # If the candidate has persisted long enough to be promoted:
        if self.Frame_classification_system[1, 2] > (thresh - 1):

            # 1. Batched Cholesky and Inversion
            chol_Qvv = LA.cholesky(self.Qvv) # (NUP, M, M)
            norm_chol = LA.norm(chol_Qvv, axis=(1, 2), keepdims=True)
            chol_inv = LA.inv(chol_Qvv + epsilon * norm_chol * np.eye(self.M))

            # 2. Transpose stand_z buffer -> (NUP, M, thresh)
            stand_z_trans = self.stand_z.transpose(1, 2, 0)

            # 3. Batched Whitening and Covariance
            # (NUP, M, M) @ (NUP, M, thresh) -> (NUP, M, thresh)
            a = chol_inv @ stand_z_trans
            # Outer product -> (NUP, M, M)
            Zvv_temp = (a @ a.conj().transpose(0, 2, 1)) / thresh

            # Update PSD
            temp_alfa = self.total_frame_per_DOA[y2_prob - 1] + thresh
            self.PSD_matrix_per_DOA[y2_prob - 1] = (self.total_frame_per_DOA[y2_prob - 1] / temp_alfa) * self.PSD_matrix_per_DOA[y2_prob - 1] + (thresh / temp_alfa) * Zvv_temp

             # 4. Slot assignment policy (Scalar state machine logic, unchanged)
            fc = self.Frame_classification_system
            if fc[1, 0] == 0:
                to_change = 0
            elif (fc[1, 1] == 0) and (abs(fc[0, 0] - y2_prob) < 3):  # Keep this threshold at 2
                to_change = 0
            elif fc[1, 1] == 0:
                to_change = 1
            else:
                to_change = np.argmin(np.abs(np.array((y2_prob, y2_prob)) - fc[0, 0:2]))
                min1, min2 = np.abs(np.array((y2_prob, y2_prob)) - fc[0, 0:2])
                if (min1 > (thresh - 2)) and (min2 > (thresh - 2)):
                    self.first_speaker_active = 1
                    self.second_speaker_active = 1
                    to_change = 0 if (self.time_first - min1 * 30) > (self.time_second - min2 * 30) else 1

            self.Frame_classification_system[0, to_change] = y2_prob
            self.Frame_classification_system[1, to_change] = self.Frame_classification_system[1, 2]
            self.Frame_classification_system[0, 2] = 0
            self.Frame_classification_system[1, 2] = 0
            self.total_frame_per_DOA[y2_prob - 1] += thresh

            # Clear candidate buffer now that it's promoted
            self.stand_z = np.empty((0, self.NUP, self.M), dtype=complex)

    def _compute_spatial_filters(self, l):
        """Applies MVDR or LCMV using fully vectorized numpy broadcasting."""
        e = self.p_beamforming['e']
        epsilon = self.p_beamforming['epsilon']
        fc = self.Frame_classification_system

        # Pre-allocate output for this frame
        s_hat = np.zeros((2, self.NUP), dtype=complex)

        # Extract the signal frame and reshape for batched multiplication: (NUP, M, 1)
        z_frame = self.z_k[l, :, :, np.newaxis]

        # Case A: No slots -> Ref mic placeholder
        if fc[0, 0] == 0 and fc[0, 1] == 0:
            s_hat[0, :] = self.z_k[l, :, 0]
            s_hat[1, :] = 1e-10

        # Case B & C require inverted Qvv. We do this once for all frequencies!
        elif fc[0, 0] != 0 or fc[0, 1] != 0:
            # Diagonal Loading: Calculate norm per frequency bin, shape (NUP, 1, 1)
            norm_Qvv = LA.norm(self.Qvv, axis=(1, 2), keepdims=True)
            reg_matrix = e * norm_Qvv * np.eye(self.M)

            # Batch invert all 1,025 matrices: (NUP, M, M)
            inv_Qvv = LA.inv(self.Qvv + reg_matrix)

            # Case B: One slot -> MVDR
            if fc[0, 0] != 0 and fc[0, 1] == 0:
                # Isolate target spatial fingerprint for Speaker 1: (NUP, M, 1)
                g = self.G[:, :, 0:1]
                g_conj = g.conj().transpose(0, 2, 1) # (NUP, 1, M)

                # Batched MVDR formula
                c = inv_Qvv @ g                        # (NUP, M, 1)
                inv_temp = (g_conj @ c) + epsilon      # (NUP, 1, 1)
                w = c / inv_temp                       # (NUP, M, 1)
                
                # Save weights
                w_flat = np.squeeze(w, axis=2)
                self.W[l, :, :, 0] = w_flat
                self.W[l, :, :, 1] = 0  # Zero out weights for the inactive speaker

                # Apply filter to signal
                s_hat_j = w.conj().transpose(0, 2, 1) @ z_frame
                s_hat_flat = np.squeeze(s_hat_j)

                # Route to Speaker 1 and mute Speaker 2
                s_hat[0, :] = s_hat_flat
                s_hat[1, :] = 1e-10

            # Case B2: Only Slot 1 active (Speaker 2 only)
            elif fc[0, 0] == 0 and fc[0, 1] != 0:
                # Isolate target spatial fingerprint for Speaker 2: (NUP, M, 1)
                g = self.G[:, :, 1:2]
                g_conj = g.conj().transpose(0, 2, 1) # (NUP, 1, M)

                # Batched MVDR formula
                c = inv_Qvv @ g                        # (NUP, M, 1)
                inv_temp = (g_conj @ c) + epsilon      # (NUP, 1, 1)
                w = c / inv_temp                       # (NUP, M, 1)

                # Save weights
                w_flat = np.squeeze(w, axis=2)
                self.W[l, :, :, 0] = 0
                self.W[l, :, :, 1] = w_flat
                
                # Apply filter to signal
                s_hat_j = w.conj().transpose(0, 2, 1) @ z_frame
                s_hat_flat = np.squeeze(s_hat_j)

                # Mute Speaker 1 and route to Speaker 2
                s_hat[0, :] = 1e-10
                s_hat[1, :] = s_hat_flat

            # Case C: Two slots -> LCMV
            elif fc[0, 0] != 0 and fc[0, 1] != 0:
                if self.flag_start_lcmv: self.flag_start_lcmv = 0

                # Target spatial fingerprints for both speakers: (NUP, M, 2)
                g = self.G
                g_conj = g.conj().transpose(0, 2, 1)   # (NUP, 2, M)

                # Batched LCMV formula
                c = inv_Qvv @ g                        # (NUP, M, 2)
                term = g_conj @ c                      # (NUP, 2, 2)

                # Diagonal loading for the inner 2x2 matrix
                norm_term = LA.norm(term, axis=(1, 2), keepdims=True)
                reg_term = e * norm_term * np.eye(self.num_speech)
                inv_temp = LA.inv(term + reg_term)     # (NUP, 2, 2)

                w = c @ inv_temp                       # (NUP, M, 2)
                self.W[l, :, :, :] = w

                # Apply filter to signal: (NUP, 2, M) @ (NUP, M, 1) -> (NUP, 2, 1)
                s_hat_j = w.conj().transpose(0, 2, 1) @ z_frame
                s_hat_flat = np.squeeze(s_hat_j, axis=2).T # Transpose to match (2, NUP) shape

                # Gating removed: let the spatial LCMV filter naturally isolate each channel.
                s_hat[0, :] = s_hat_flat[0, :]
                s_hat[1, :] = s_hat_flat[1, :]

        # Aggregate outputs
        if l == 0:
            self.s_hat_total = s_hat.T.reshape(1, self.NUP, self.num_speech)
        else:
            self.s_hat_total = np.concatenate((self.s_hat_total, s_hat.T.reshape(1, self.NUP, self.num_speech)), axis=0)

    def run_online_separation(self):
        """Executes the main online tracking and separation loop."""
        if self.verbose: print("--- Running Online Separation ---")

        for l in range(len(self.y2_prob_stat_mf)):
            if self.verbose > 1 and l % 100 == 0:
                print(f"Processing frame {l}/{len(self.y2_prob_stat_mf)}")

            y_prob = self.y_prob_stat_mf[l]

            if y_prob == 0:
                self._update_noise_covariance(l)
            elif y_prob == 1:
                self._update_rtf_and_tracking(l)

            elif y_prob == 2:
                self.first_speaker_active = 1
                self.second_speaker_active = 1
                self.time_second += 1
                self.time_first += 1

            self._compute_spatial_filters(l)

    def reconstruct_audio(self):
        """Converts filtered frequency features back to time-domain audio."""
        if self.verbose: print("--- Reconstructing Audio (ISTFT) ---")

        win = self.p_stft['win']

        hop = self.p_stft['hop']
        nfft = self.p_stft['nfft']

        self.speech_out = []
        for p in range(self.num_speech):
            speech, _ = istft(self.s_hat_total[:, :, p].T, win, win, hop, nfft, self.fs)
            self.speech_out.append(speech)

    def evaluate_and_save(self):
        """Saves outputs to disk and calculates metrics if reference files exist."""
        if self.verbose: print("--- Saving Outputs ---")

        # Ensure the results folder exists
        os.makedirs(self.folder_to_results, exist_ok=True)

        # Save separated sources
        for p in range(self.num_speech):
            output_path = os.path.join(self.folder_to_results, f'separating_speaker_{p}_{self.run_idx}.wav')
            wavfile.write(output_path, self.fs, self.speech_out[p])

        if not self.evaluate: return

        if self.verbose: print("--- Computing Evaluation Metrics ---")
        win = self.p_stft['win']
        hop = self.p_stft['hop']
        nfft = self.p_stft['nfft']

        # Isolate overlap interval
        start_overlap = np.nonzero(self.y_mf == 2)[0][0]
        finish_overlap = np.nonzero(self.y_mf == 2)[0][-1]

        s_hat_overlap = self.s_hat_total[start_overlap:finish_overlap]

        z_first_overlap = self.z_k_first[start_overlap:finish_overlap]
        z_second_overlap = self.z_k_second[start_overlap:finish_overlap]

        s_hat_1_time, _ = istft(s_hat_overlap[:, :, 0].T, win, win, hop, nfft, self.fs)
        s_hat_2_time, _ = istft(s_hat_overlap[:, :, 1].T, win, win, hop, nfft, self.fs)
        ref_1_time, _ = istft(z_first_overlap[:, :, 0].T, win, win, hop, nfft, self.fs)
        ref_2_time, _ = istft(z_second_overlap[:, :, 0].T, win, win, hop, nfft, self.fs)

        ref_sources = np.concatenate((ref_1_time.reshape(-1, 1), ref_2_time.reshape(-1, 1)), axis=1)
        est_sources = np.concatenate((s_hat_1_time.reshape(-1, 1), s_hat_2_time.reshape(-1, 1)), axis=1)

        # BSS Eval
        sdr, sir, sar, perm = mir_eval.separation.bss_eval_sources(ref_sources.T + 1e-9, est_sources.T, compute_permutation=True)

        if self.verbose:
            print("\n--- Evaluation Results (During Overlap) ---")
            print(f"Speaker 0 -> SDR: {sdr[0]:.2f} dB | SIR: {sir[0]:.2f} dB | SAR: {sar[0]:.2f} dB")
            print(f"Speaker 1 -> SDR: {sdr[1]:.2f} dB | SIR: {sir[1]:.2f} dB | SAR: {sar[1]:.2f} dB")
            print("-" * 45)
            print(f"Average   -> SDR: {sdr.mean():.2f} dB | SIR: {sir.mean():.2f} dB | SAR: {sar.mean():.2f} dB")

        # Return the mean evaluation metrics for external tracking
        return sdr.mean(), sir.mean(), sar.mean()

    def investigate_geometry(self):
        """
        Diagnoses the acoustic geometry of the current audio file.
        1. Extracts the physical DOA index for each speaker.
        2. Calculates the spatial correlation between the dominant noise direction
           and each speaker's spatial fingerprint.
        """
        print("\n" + "="*55)
        print(" ACOUSTIC GEOMETRY INVESTIGATION")
        print("="*55)

        # ---------------------------------------------------------
        # 1. Speaker Direction of Arrival (DOA) Indices
        # ---------------------------------------------------------
        print("\n[1] Microphone Array Geometry (DOA Sectors per Speaker):")

        # Extract frames where only one speaker is active (CSD=1)
        single_frames_idx = np.where(self.y_prob_stat_mf == 1)[0]
        doas_single = self.y2_prob_stat_mf[single_frames_idx]

        # Measure output energy to know WHICH speaker was active in those frames
        power_0 = np.mean(np.abs(self.s_hat_total[single_frames_idx, :, 0])**2, axis=1)
        power_1 = np.mean(np.abs(self.s_hat_total[single_frames_idx, :, 1])**2, axis=1)

        # Assign DOAs to Speaker 0 when its output energy is significantly higher
        doas_spk0 = doas_single[power_0 > power_1 * 10]
        # Assign DOAs to Speaker 1 when its output energy is significantly higher
        doas_spk1 = doas_single[power_1 > power_0 * 10]

        unique_doas_0 = np.unique(doas_spk0[doas_spk0 > 0]).astype(int)
        unique_doas_1 = np.unique(doas_spk1[doas_spk1 > 0]).astype(int)

        print(f"    Speaker 0 is moving through sectors: {unique_doas_0}")
        print(f"    Speaker 1 is moving through sectors: {unique_doas_1}")
        print("    -> Note: The array spans 180 degrees (Indices 1 to 18).")
        print("    -> 'Broadside' (Optimal separation) is around index 9.")
        print("    -> 'Endfire' (Poor separation) is near index 1 or 18.")

        # ---------------------------------------------------------
        # 2. Spatial Correlation with Directional Noise
        # ---------------------------------------------------------
        print("\n[2] Spatial Overlap (Speaker vs. Background Noise):")
        correlation_scores = np.zeros(self.num_speech)

        for p in range(self.num_speech):
            corr_per_freq = np.zeros(self.NUP)

            for f in range(self.NUP):
                # Target spatial fingerprint
                g_f = self.G[f, :, p]

                # Eigendecomposition of the noise matrix
                w, v = np.linalg.eig(self.Qvv[f, :, :])

                # Dominant noise direction is the eigenvector of the largest eigenvalue
                noise_vector = v[:, np.argmax(w.real)]

                # Complex Cosine Similarity
                numerator = np.abs(np.vdot(g_f, noise_vector))**2
                denominator = (np.linalg.norm(g_f)**2) * (np.linalg.norm(noise_vector)**2)
                corr_per_freq[f] = numerator / (denominator + 1e-15)

            correlation_scores[p] = np.mean(corr_per_freq)
            print(f"    Speaker {p} Spatial Overlap: {correlation_scores[p]:.4f}")

        print("\n    -> Score Guide: 0.0 means completely orthogonal (perfect).")
        print("    -> Score Guide: 1.0 means exact same direction (impossible to separate).")
        print("="*55 + "\n")

    def compute_noise_reduction(self):
        """
        Calculates the quantitative Noise Reduction (NR) in dB.
        1. Calculates the true final target NR using shared late valid frames.
        2. Uses a moving average over early frames to find when Speaker 0 hits 95% of its target.
        3. Compares the average of all valid frames vs the converged frames.
        """
        if self.verbose: print("\n--- Computing Noise Reduction Metrics ---")

        noise_frames_idx = np.where(self.y_prob_stat_mf == 0)[0]

        if len(noise_frames_idx) == 0:
            if self.verbose: print("No pure noise frames found to evaluate.")
            return None, None

        # Energy per frame for input (Mic 0) and outputs
        power_in_frames = np.mean(np.abs(self.z_k[noise_frames_idx, :, 0])**2, axis=1)
        power_out_frames = np.zeros((self.num_speech, len(noise_frames_idx)))
        for p in range(self.num_speech):
            power_out_frames[p, :] = np.mean(np.abs(self.s_hat_total[noise_frames_idx, :, p])**2, axis=1)

        valid_idx_0 = np.where(power_out_frames[0, :] > 1e-18)[0]
        valid_idx_1 = np.where(power_out_frames[1, :] > 1e-18)[0]

        # ---------------------------------------------------------
        # Part 1: Fair "Apples-to-Apples" NR Comparison (The Target)
        # ---------------------------------------------------------
        shared_valid_idx = np.intersect1d(valid_idx_0, valid_idx_1)

        target_nr = [0.0, 0.0]

        if len(shared_valid_idx) > 0:
            if self.verbose: print(f"\n[1] Fair Noise Attenuation (Over {len(shared_valid_idx)} shared valid frames):")
            mean_power_in_shared = np.mean(power_in_frames[shared_valid_idx])

            for p in range(self.num_speech):
                mean_power_out_shared = np.mean(power_out_frames[p, shared_valid_idx])
                target_nr[p] = 10 * np.log10(mean_power_in_shared / (mean_power_out_shared + 1e-15))
                if self.verbose: print(f"    - Speaker {p} Channel: Final target NR = {target_nr[p]:.2f} dB")
        else:
            print("    - No shared valid frames found. Cannot compute target NR.")
            return None, None

        # ---------------------------------------------------------
        # Part 2: Empirical Convergence Time (Speaker 0)
        # ---------------------------------------------------------
        # We look at the frames for Speaker 0 before Speaker 1 became valid
        early_frames_0 = np.setdiff1d(valid_idx_0, shared_valid_idx)

        if len(early_frames_0) > 0 and target_nr[0] > 0:
            if self.verbose: print("\n[2] Empirical Convergence Analysis (Speaker 0):")

            # The target is 95% of the final stable NR calculated in Part 1
            threshold_db = target_nr[0] * 0.95
            print(f"    - Target NR: {target_nr[0]:.2f} dB (95% Threshold: {threshold_db:.2f} dB)")

            # Use a moving average window to smooth frame-to-frame variance
            window_size = 10
            convergence_frame_count = 0
            converged = False

            for i in range(len(early_frames_0) - window_size):
                window_idx = early_frames_0[i:i+window_size]

                # Mean energy over the sliding window
                win_power_in = np.mean(power_in_frames[window_idx])
                win_power_out = np.mean(power_out_frames[0, window_idx])
                win_nr_db = 10 * np.log10(win_power_in / (win_power_out + 1e-15))

                if win_nr_db >= threshold_db:
                    # Plus window_size/2 to approximate the center of the window
                    convergence_frame_count = i + (window_size // 2)
                    converged = True
                    break

            if converged:
                print(f"    - Frames to reach 95% convergence: ~{convergence_frame_count} frames")
            else:
                print("    - Speaker 0 did not clearly hit the 95% threshold before the shared phase.")

        # ---------------------------------------------------------
        # Part 3: Final Sanity Check (All frames vs. Converged)
        # ---------------------------------------------------------
        if len(early_frames_0) > 0 and len(shared_valid_idx) > 0:
            if self.verbose: print("\n[3] Sanity Check: All Frames vs Converged Frames (Speaker 0):")

            # Combine early frames and shared valid frames
            all_valid_idx = np.union1d(early_frames_0, shared_valid_idx)

            mean_power_in_all = np.mean(power_in_frames[all_valid_idx])
            mean_power_out_all = np.mean(power_out_frames[0, all_valid_idx])
            nr_all_db = 10 * np.log10(mean_power_in_all / (mean_power_out_all + 1e-15))

            print(f"    - NR for Speaker 0 (All valid frames): {nr_all_db:.2f} dB")
            print(f"    - NR for Speaker 0 (Converged frames only): {target_nr[0]:.2f} dB")

        # Return the target noise reduction for both speakers
        return target_nr[0], target_nr[1]

    def run(self):
        """Orchestrates the separation pipeline with timing."""
        print(f"\n{'='*55}")
        print(f" STARTING PIPELINE EXECUTION (Experiment {self.run_idx})")
        print(f"{'='*55}")

        total_start = time.time()

        # 1. Load Data
        step_start = time.time()
        self.load_data()
        t_load = time.time() - step_start
        print(f"[⏱] 1. Load Data:                  {t_load:>6.2f} seconds")

        # 2. Compute STFT
        step_start = time.time()
        self.compute_stft()
        t_stft = time.time() - step_start
        print(f"[⏱] 2. Compute STFT:               {t_stft:>6.2f} seconds")

        # 3. Online Separation (The heavy lifting)
        step_start = time.time()
        self.run_online_separation()
        t_sep = time.time() - step_start
        print(f"[⏱] 3. Run Online Separation:      {t_sep:>6.2f} seconds")

        # Print time per frame for the online separation step
        if self.verbose > 1:
            num_frames = len(self.y2_prob_stat_mf)
            time_per_frame = t_sep / num_frames
            print(f"     - Time per frame: {time_per_frame:.4f} seconds/frame")

        # 4. Reconstruct Audio (ISTFT)
        step_start = time.time()
        self.reconstruct_audio()
        t_recon = time.time() - step_start
        print(f"[⏱] 4. Reconstruct Audio:          {t_recon:>6.2f} seconds")

        # 5. Evaluate and Save
        step_start = time.time()

        # Capture the returned metrics if evaluation is possible
        if self.evaluate:
            sdr_avg, sir_avg, sar_avg = self.evaluate_and_save()
        else:
            self.evaluate_and_save()
            sdr_avg, sir_avg, sar_avg = None, None, None

        t_eval = time.time() - step_start
        print(f"[⏱] 5. Evaluate and Save:          {t_eval:>6.2f} seconds")

        total_time = time.time() - total_start
        print(f"{'-'*55}")
        print(f" TOTAL EXECUTION TIME:             {total_time:>6.2f} seconds")
        print(f"{'='*55}\n")

        self.investigate_geometry()

        # Capture NR metrics
        nr_0, nr_1 = self.compute_noise_reduction()

        # Return all 5 metrics to the orchestrator script
        return sdr_avg, sir_avg, sar_avg, nr_0, nr_1

if __name__ == "__main__":
    # Dynamically locate the workspace
    py_folder = os.path.dirname(os.path.realpath(__file__))
    workspace_folder = py_folder
    folder_to_all_data = os.path.join(workspace_folder, 'data')
    folder_to_test_data = os.path.join(folder_to_all_data, 'simulated_audio', 'test', 'concurrent_dynamic')

    # Define where the tracking pipeline saved its labels, and where we will save the separated audio
    folder_to_results = os.path.join(workspace_folder, 'pipeline_results', 'dynamic')

    # Configuration objects (same as before)
    p_stft = {
        'nfft': 2048,
        'wlen': 2048,
        'hop': 512,  # wlen / 4
        'NUP': 1025,
        'win': np.hamming(2048)
    }

    p_tracking = {
        'frame_before': 8,
        'frame_after': 5,
        'win_vad': np.hamming(21),
        'threshold': 40,
        'threshold_freq': 0.3,
        'threshold_chage_location': 8
    }

    p_beamforming = {
        'e': 0.01,
        'epsilon': 0.01,
        'alfa_Qvv_init': 0.99,
        'alfa_Qvv_run': 0.05,
        'buffer_size': 32
    }

    # Instantiate and run
    pipeline = SpatialSeparationPipeline(
        run_idx=1,
        p_stft=p_stft,
        p_tracking=p_tracking,
        p_beamforming=p_beamforming,
        folder_to_test_data=folder_to_test_data,
        folder_to_results=folder_to_results,
        M=4,
        verbose=2
    )

    pipeline.run()